ccflags-y := -Iinclude/drm

gm12u320-y :=	gm12u320_drv.o gm12u320_modeset.o gm12u320_connector.o \
		gm12u320_encoder.o gm12u320_main.o gm12u320_fb.o \
		gm12u320_gem.o gm12u320_dmabuf.o

obj-$(CONFIG_DRM_GM12U320) += gm12u320.o
