vpd-sysfs-y := vpd.o vpd_decode.o

obj-$(CONFIG_GOOGLE_SMI)		+= gsmi.o
obj-$(CONFIG_GOOGLE_COREBOOT_TABLE)	+= coreboot_table.o
obj-$(CONFIG_GOOGLE_MEMCONSOLE_OF)	+= memconsole-of.o
obj-$(CONFIG_GOOGLE_MEMCONSOLE_X86)	+= memconsole-x86.o
obj-$(CONFIG_GOOGLE_MEMCONSOLE)		+= memconsole.o
obj-$(CONFIG_GOOGLE_VPD)		+= vpd-sysfs.o
